language: node_js
node_js:
  - "10.0.0"
sudo: false

notifications:
  email:
    - chiu@aftership.com
env:
  - CACHE_DIR=cache
cache:
  directories:
    - $CACHE_DIR
branches:
  only:
    - master
install:
  - . ./scripts/ci/setup.sh
script:
  - . ./scripts/ci/run.sh

after_script:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN